runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /.*
  script: gaend.main.APP

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: pycrypto
  version: "2.6"
- name: ssl
  version: latest
